Movie.WEBUI/Components/MovieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.DAL.Data;

namespace Movie.WEBUI.Components
{
    public class MovieViewComponent : ViewComponent
    {
        readonly AppDbContext db;
      
        public MovieViewComponent(AppDbContext db)
        {
         this.db = db;
        }


        public Task<IViewComponentResult> InvokeAsync(int trendId, int categoryId, bool top =false,bool isneww=false)
        {
            var movies = db.Movies.Include(p=>p.GenresCategory)
                .Include(p => p.CountryCategory)
                .Include(p=>p.Trend)
                .Include(p => p.LanguageCategory).AsNoTracking().ToList();

            if(trendId > 0)
            {
                movies = movies.Where(p=>p.TrendId== trendId).ToList();
            }
            if (isneww == true)
            {
                movies = movies.Where(p => p.isneww == true).ToList();
                ViewBag.isneww = "true";
            }

            if (categoryId > 0)
            {
                movies = movies.Where(p => p.GenresCategoryId == categoryId).Take(5).ToList();
            }
            if(top == true)
            {
               movies = movies.Where(p => p.Top == true).ToList();
            }

            return Task.FromResult<IViewComponentResult>(View(movies));

        }
    }
}

Movie.WEBUI/Components/OtherMovieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movie.WEBUI.ViewModels;
using Movies.DAL.Data;
using Movies.DAL.DbModel;

namespace Movie.WEBUI.Components
{
    public class OtherMovieViewComponent : ViewComponent
    {
        readonly AppDbContext db;

        public OtherMovieViewComponent(AppDbContext db)
        {
            this.db = db;
        }


        public Task<IViewComponentResult> InvokeAsync(int PageIndex = 1, int pagSize = 12)
        {
            var vm = new HomeViewModel();

          vm.PagedViewModel  = new PagedViewModel<MovieC>(db.Movies.Include(p => p.GenresCategory).Include(p => p.CountryCategory).Include(p => p.Trend).Include(p => p.LanguageCategory), PageIndex, pagSize);
            return Task.FromResult<IViewComponentResult>(View(vm));

        }
    }
}

Movie.WEBUI/Components/SigninViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Movies.DAL.Data;

namespace Movie.WEBUI.Components
{
    public class SigninViewComponent : ViewComponent
    {
        readonly AppDbContext db;

        public SigninViewComponent(AppDbContext db)
        {
            this.db = db;
        }


        public Task<IViewComponentResult> InvokeAsync()
        {

            return Task.FromResult<IViewComponentResult>(View());

        }
    }
}

Movie.WEBUI/Controllers/PlayMoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movie.WEBUI.ViewModels;
using Movies.DAL.Data;
using Movies.DAL.DbModel;

namespace Movie.WEBUI.Controllers
{
    public class PlayMoviesController : Controller
	{
        private readonly AppDbContext _context;

        public PlayMoviesController(AppDbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index(int id)
        {
            var movie = await _context.Movies.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);
            if (movie != null)
            {
                _context.Entry(movie).State = EntityState.Modified;
                movie.ViewsCount += 1;
                await _context.SaveChangesAsync();
            }

            var vm = new HomeViewModel
            {
                MovieC = movie
            };

            return View(vm);
        }



    }
}

Movie.WEBUI/Views/Shared/Components/Movie/Default.cshtml
@model IEnumerable<MovieC>

@if (string.IsNullOrWhiteSpace(ViewBag.isneww))
{
    @foreach (var item in Model)
    {
        <div class="img-div @(item.LanguageCategoryId == 7 ? "turkish" : "")">
            <div class="card-language">
                <div class="turkish-text-container">
                    @if (item.LanguageCategoryId==7)
                    {
                        <span class="turkish-text">Türkçe</span>
                    }
                </div>
                <img src="~/@item.Img" alt="" id="image" class="img-fluid" loading="lazy">
                <div class="icon-container me-2">
                    <a asp-area="" asp-controller="PlayMovies" asp-action="Index" asp-route-id="@item.Id"><i class="bi bi-play-circle "></i></a>
                    <a href=""><i class="bi bi-plus-circle-dotted"></i></a>
                    <a href=""><i class="bi bi-info-circle"></i></a>
                </div>
            </div>
            <h4 style="color:red;">@item.Name </h4>
            <p class="text-white"> @item.Year <span style="color:red;">||</span> </p>
            <p class="mx-2 text-white">@item.Age<span style="color:red;">+ ||</span></p>
            <p class="text-white">@item.GenresCategory.Name</p>
        </div>
    }
}
else
{
    @foreach (var item in Model)
    {
        <div class="slider-item" style="background: url(/@item.Img); background-size: cover; ">
            <div class="slider-content-main">
                <div class="slider-content">
                    <span class="badge mb-4">New</span>
                    <h1>@item.Name</h1>
                    <p>
                        @item.Description
                    </p>
                    <div class="SpanMovies my-5">
                        <span><i class="bi bi-person-fill"></i>@item.Age+</span>
                        <span><i class="bi bi-clock"></i>@item.MovieTime</span>
                        <span><i class="bi bi-emoji-smile"></i>@item.Year</span>
                        <span><i class="bi bi-activity"></i>@item.GenresCategory.Name</span>
                        <span><i class="bi bi-globe"></i>@item.CountryCategory.Name</span>
                    </div>
                    <div class="slider-action">
                        <a asp-area="" asp-controller="PlayMovies" asp-action="Index" asp-route-id="@item.Id" style="border-radius:0;"
                        class="slider-btn-1">Play Now</a>
                    </div>
                </div>
            </div>
        </div>
    }

}


@section Scripts {

    <script>
        $(document).ready(function () {
            // Fərəni yalnız 'turkish' classına malik kartların üzərinə gətirəndə hadisələr təyin edirik.
            $('.img-div.turkish > div').hover(function () {
                // Burada yalnız 'turkish' classı olan kartlar üçün transformasiya tətbiq edirik
                $(this).find('img').css({ 'transform': 'scale(1.2)', 'transition': 'transform 0.5s', 'z-index': '1' });
            }, function () {
                // Burada transformasiya ləğv edilir
                $(this).find('img').css({ 'transform': 'scale(1)', 'z-index': '0' });
            });
        });

    </script>
}