Movie.WEBUI/ViewModels/HomeViewModel.cs
using Movie.WEBUI.wwwroot.ViewModels;
using Movies.DAL.DbModel;
using Movies.DAL.Dtos;

namespace Movie.WEBUI.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Trends>? Trends { get; set; }
        public IEnumerable<GenresCategory>? GenresCategories { get; set; }
        public IEnumerable<CountryCategory>? CountryCategories { get; set; }
        public IEnumerable<LanguageCategory>? LanguageCategories { get; set; }
        public SignInViewModel SignInViewModel { get; set; }
        public MovieC MovieC { get; set; }
        public SignUpViewModel? SignUpViewModel { get; set; }
        public ProfileViewModel? ProfileViewModel { get; set; }
        public PagedViewModel<MovieC> PagedViewModel { get; set; }
        public IEnumerable<AboutDto>? Abouts { get; set; }

        public FilterFormModel FilterFormModel { get; set; }
    }
}

Movie.WEBUI/Components/MovieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.DAL.Data;

namespace Movie.WEBUI.Components
{
    public class MovieViewComponent : ViewComponent
    {
        readonly AppDbContext db;
      
        public MovieViewComponent(AppDbContext db)
        {
         this.db = db;
        }


        public Task<IViewComponentResult> InvokeAsync(int trendId, int categoryId, bool top =false,bool isneww=false)
        {
            var movies = db.Movies.Include(p=>p.GenresCategory)
                .Include(p => p.CountryCategory)
                .Include(p=>p.Trend)
                .Include(p => p.LanguageCategory).AsNoTracking().ToList();

            if(trendId > 0)
            {
                movies = movies.Where(p=>p.TrendId== trendId).ToList();
            }
            if (isneww == true)
            {
                movies = movies.Where(p => p.isneww == true).ToList();
                ViewBag.isneww = "true";
            }

            if (categoryId > 0)
            {
                movies = movies.Where(p => p.GenresCategoryId == categoryId).Take(5).ToList();
            }
            if(top == true)
            {
               movies = movies.Where(p => p.Top == true).ToList();
            }

            return Task.FromResult<IViewComponentResult>(View(movies));

        }
    }
}

Movie.WEBUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movie.WEBUI.Models;
using Movie.WEBUI.ViewModels;
using Movies.DAL.Data;
using System.Diagnostics;

namespace Movie.WEBUI.Controllers
{
	public class HomeController : Controller
	{
		readonly AppDbContext db;
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger, AppDbContext db)
		{
			_logger = logger;
			this.db = db;
		}

		public IActionResult Index()
		{
			var vm = new HomeViewModel();
			//vm.Trends = db.Trends.ToList();
			vm.GenresCategories= db.GenresCategories.ToList();	
			return View(vm);
		}

        public IActionResult AccessDenied()
        {

            return View();
        }

        public IActionResult Privacy()
		{
			return View();
		}


		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Movie.WEBUI/Views/Home/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
}

<link rel="stylesheet" href="~/css/404.css" asp-append-version="true">

<div id="pagenotfound">
    <div class="pagenotfound">
        <div class="notfound404">
            <h1>404</h1>
        </div>
        <h2>page not found</h2>
        <p>The page you are you looking for might have been removed had its name changed or is temporarily unavailable</p>
        <a asp-controller="Home" asp-page="AccessDenied">Go to Homepage</a>
    </div>
</div>

Movie.WEBUI/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
    int count = 0;
}

<div class="hero-slider owl-carousel owl-theme ">
    <!--Esas Carusel-->
    <!--item-->
    @await Component.InvokeAsync("Movie", new{isneww = true})
    <!--item-->
</div>
<div class="container">
    <div id="moviesCarusel">
        <!--Featured,Movies,Shows Carusel-->
        <div class="row">
            <div class="movie-category">
                <ul class="featured-movies-shows">

                    @foreach (var item in Model.GenresCategories.Where(gc => gc.Name.Contains("Action") || gc.Name.Contains("Sport")))
                    {
                        <li class=" active px-3 me-4" data-category="@item.Name">@item.Name</li>
                    }

                </ul>
                <div class="images container">
                    @foreach (var item in Model.GenresCategories.Where(gc => gc.Name.Contains("Action") || gc.Name.Contains("Sport")))
                    {
                        count++;
                        if (count == 1)
                        {
                            <div class="carousel owl-carousel imageJ @item.Name active text-white">

                                @await Component.InvokeAsync("Movie", new { categoryId = item.Id })

                            </div>
                        }
                        else
                        {
                            <div class="carousel owl-carousel imageJ @item.Name  text-white">
                                @await Component.InvokeAsync("Movie", new { categoryId = item.Id })
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper">
        <!--Comedia Movies Carusel-->
        <h2>Comedia</h2>
        <hr id="hr_color">
        @foreach (var item in Model.GenresCategories.Where(gc => gc.Name.Contains("Comedia")))
        {
            <div class="carousel owl-carousel @item.Name">

                @await Component.InvokeAsync("Movie", new{categoryId = item.Id})

            </div>
        }
    </div>
    <div class="container Suggested">
        <!--Top 5 Carusel-->
        <div>
            <h2 class="text-white fw-bolder">Top 5</h2>
            <hr id="hr_color">
            <div class="carousel owl-carousel">
                @foreach (var item in Model.GenresCategories)
                {

                    @await Component.InvokeAsync("Movie", new{Top = true})

                }
            </div>
        </div>
    </div>
    <div class="TrendingNow ">
        <!--History  Carusel-->
        <h2 class="text-white fw-bolder">History</h2>
        <hr id="hr_color">
        @foreach (var item in Model.GenresCategories.Where(gc => gc.Name.Contains("History")))
        {
            <div class="carousel owl-carousel @item.Name">
                @await Component.InvokeAsync("Movie", new{categoryId = item.Id})
            </div>
        }
    </div>
</div>
<div class="container-fluid BestSeries">
    <!--Best Series Carusel-->
    <div class="container">
        <h3>Featured</h3>
        <h1>Best Series</h1>
        <div id="moviesCarusel">
            <!--Drama,Family,Romance Carusel-->
            <div class="movie-category">
                <ul class="BestSeries_li text-center">
                    @foreach (var item in Model.GenresCategories.Where(gc => gc.Name.Contains("Drama") || gc.Name.Contains("Family") || gc.Name.Contains("Romance")))
                    {

                        <li class=" active px-3 me-4 " data-category="@item.Name">@item.Name</li>

                    }
                </ul>
                @(count = 0)
                <div class="images container ">

                    @foreach (var item in Model.GenresCategories.Where(gc => gc.Name.Contains("Drama") || gc.Name.Contains("Family") || gc.Name.Contains("Romance")))
                    {
                        count++;
                        if (count == 1)
                        {
                            <div class="carousel owl-carousel  image @item.Name active text-white">

                                @await Component.InvokeAsync("Movie", new { categoryId = item.Id })

                            </div>
                        }
                        else
                        {
                            <div class="carousel owl-carousel  image @item.Name  text-white">

                                @await Component.InvokeAsync("Movie", new { categoryId = item.Id })

                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container Suggested">
    <!--Animation Carusel-->
    <div>
        <h2 class="text-white fw-bolder">Animation</h2>
        <hr id="hr_color">
        @foreach (var item in Model.GenresCategories.Where(gc => gc.Name.Contains("Animation")))
        {
            <div class="carousel owl-carousel @item.Name">
                @await Component.InvokeAsync("Movie",new{categoryId = item.Id})
            </div>
        }
    </div>
</div>